### ISSUE TITLE
Adding Ingredients 

### ISSUE THREAD

**Issue by ghost307** [alex9849/pi-cocktail-maker#29]
Everything with this project has been going smoothly, the only issue that I have is that it only let me add certain ingredients to the pumps. Simple ingredients like vodka, tequila, rum, etc. Any fix for this issue?

**Comment by alex9849** [comment]
You can add all ingredients to pumps that are stored as automated ingredients. Obviously ingredients that can only be added by hand can't get added. Regarding ingredients groups you should know that these have been implemented with a specific role in mind:
Normal Ingredients should be concrete ingredients that you can actually buy. For example Jack Daniel'S Old N°7.
This ingredients could again be a member of the group Bourbon which again would be a member of Whisky.

If you now have a recipe that requires Whisky or Bourbon, you could use that Jack Daniel's ingredients as a substitute. This makes sense, since Jack Daniel's is exactly that. A Whisky/Bourbon. But this doesn't work the other way around. If you have a recipe that requires Jack Daniel's you can't just use any other whisky. That's why you can't assign ingredient groups directly to pumps. The substitution process only works in one direction.

**Comment by alex9849** [comment]
Does this help?

**Comment by ghost307** [comment]
Right now the software for the cocktail maker is v0.6.1 and i see that the
version that you made a demo is v0.8.7. I was wondering how do i get to
that version of the software because everything that I try isnt updating
the software.

**Comment by alex9849** [comment]
As root user while the second command should point to the folder where your cocktailmaker.jar is located in:
`
service cocktailmaker stop
cd /root/cocktailmaker
wget https://github.com/alex9849/pi-cocktail-maker/releases/latest/download/server.jar -O cocktailmaker.jar
sudo systemctl daemon-reload
sudo update-rc.d cocktailmaker defaults
service cocktailmaker start
`
